try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var s_1Dd=function(a,b,c,d,e,f,g){a="number"===typeof a?Date.UTC(a,b||0,c||1,d||0,e||0,f||0,g||0):a?a.getTime():s_Re();this.date=new Date(a)};s_Se(s_1Dd,s_jx);s_=s_1Dd.prototype;s_.clone=function(){var a=new s_1Dd(this.date);a.v7=this.v7;a.Lxa=this.Lxa;return a};s_.add=function(a){(a.oa||a.Tw)&&s_gx.prototype.add.call(this,new s_fx(a.oa,a.Tw));a=1E3*(a.ka+60*(a.minutes+60*(a.hours+24*a.Sn)));this.date=new Date(this.date.getTime()+a)};s_.getTimezoneOffset=function(){return 0};s_.getFullYear=s_jx.prototype.getUTCFullYear;
s_.getMonth=s_jx.prototype.getUTCMonth;s_.getDate=s_jx.prototype.getUTCDate;s_.getHours=s_jx.prototype.getUTCHours;s_.getMinutes=s_jx.prototype.getUTCMinutes;s_.getSeconds=s_jx.prototype.getUTCSeconds;s_.getMilliseconds=s_jx.prototype.getUTCMilliseconds;s_.getDay=s_jx.prototype.getUTCDay;s_.setFullYear=s_jx.prototype.setUTCFullYear;s_.setMonth=s_jx.prototype.setUTCMonth;s_.setDate=s_jx.prototype.setUTCDate;s_.setHours=s_jx.prototype.setUTCHours;s_.setMinutes=s_jx.prototype.setUTCMinutes;
s_.setSeconds=s_jx.prototype.setUTCSeconds;s_.setMilliseconds=s_jx.prototype.setUTCMilliseconds;

}catch(e){_DumpException(e)}
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var s_2Dd=function(a){return s_oQc(a.getFullYear(),a.getMonth())},s_3Dd=function(a,b,c,d,e){a=new Date(a,b,c);d=void 0!==d?d:3;e=e||0;b=((a.getDay()+6)%7-e+7)%7;return a.valueOf()+864E5*((d-e+7)%7-b)};
var s_4Dd=function(){},s_tC=function(a){if("number"==typeof a){var b=new s_4Dd;b.Ba=a;var c=a;if(0==c)c="Etc/GMT";else{var d=["Etc/GMT",0>c?"-":"+"];c=Math.abs(c);d.push(Math.floor(c/60)%100);c%=60;0!=c&&d.push(":",s_0g(c,2));c=d.join("")}b.wa=c;c=a;0==c?c="UTC":(d=["UTC",0>c?"+":"-"],c=Math.abs(c),d.push(Math.floor(c/60)%100),c%=60,0!=c&&d.push(":",c),c=d.join(""));a=s_5Dd(a);b.Aa=[c,c];b.ka={ymf:a,Lkc:a};b.oa=[];return b}b=new s_4Dd;b.wa=a.id;b.Ba=-a.std_offset;b.Aa=a.names;b.ka=a.names_ext;b.oa=
a.transitions;return b},s_5Dd=function(a){var b=["GMT"];b.push(0>=a?"+":"-");a=Math.abs(a);b.push(s_0g(Math.floor(a/60)%100,2),":",s_0g(a%60,2));return b.join("")},s_6Dd=function(a,b){b=Date.UTC(b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate(),b.getUTCHours(),b.getUTCMinutes())/36E5;for(var c=0;c<a.oa.length&&b>=a.oa[c];)c+=2;return 0==c?0:a.oa[c-1]},s_7Dd=function(a,b){a=a.Ba-s_6Dd(a,b);return-1440===a?0:a};
var s_uC=function(a,b){this.oa=[];this.ka=b||s_ex;"number"==typeof a?s_8Dd(this,a):s_9Dd(this,a)},s_$Dd=[/^'(?:[^']|'')*('|$)/,/^(?:G+|y+|Y+|M+|k+|S+|E+|a+|b+|B+|h+|K+|H+|c+|L+|Q+|d+|m+|s+|v+|V+|w+|z+|Z+)/,/^[^'GyYMkSEabBhKHcLQdmsvVwzZ]+/],s_aEd=function(a){return a.getHours?a.getHours():0},s_9Dd=function(a,b){for(s_bEd&&(b=b.replace(/\u200f/g,""));b;){for(var c=b,d=0;d<s_$Dd.length;++d){var e=b.match(s_$Dd[d]);if(e){var f=e[0];b=b.substring(f.length);0==d&&("''"==f?f="'":(f=f.substring(1,"'"==e[1]?
f.length-1:f.length),f=f.replace(/''/g,"'")));a.oa.push({text:f,type:d});break}}if(c===b)throw Error("Kh`"+b);}};
s_uC.prototype.format=function(a,b){if(!a)throw Error("Lh");var c=b?6E4*(a.getTimezoneOffset()-s_7Dd(b,a)):0,d=c?new Date(a.getTime()+c):a,e=d;b&&d.getTimezoneOffset()!=a.getTimezoneOffset()&&(e=6E4*(d.getTimezoneOffset()-a.getTimezoneOffset()),d=new Date(d.getTime()+e),c+=0<c?-864E5:864E5,e=new Date(a.getTime()+c));c=[];for(var f=0;f<this.oa.length;++f){var g=this.oa[f].text;1==this.oa[f].type?c.push(s_cEd(this,g,a,d,e,b)):c.push(g)}return c.join("")};
var s_8Dd=function(a,b){if(4>b)var c=a.ka.rua[b];else if(8>b)c=a.ka.fva[b-4];else if(12>b)c=a.ka.Bec[b-8],c=c.replace("{1}",a.ka.rua[b-8]),c=c.replace("{0}",a.ka.fva[b-8]);else if(12===b)c=a.ka.rua[0].replace(/[^EMd]*yy*[^EMd]*/,"");else{s_8Dd(a,10);return}s_9Dd(a,c)},s_vC=function(a,b){b=String(b);a=a.ka||s_ex;if(void 0!==a.FDb){for(var c=[],d=0;d<b.length;d++){var e=b.charCodeAt(d);c.push(48<=e&&57>=e?String.fromCharCode(a.FDb+e-48):b.charAt(d))}b=c.join("")}return b},s_bEd=!1,s_dEd=function(a){if(!(a.getHours&&
a.getSeconds&&a.getMinutes))throw Error("Mh");},s_eEd=function(a,b){s_dEd(b);b=s_aEd(b);return a.ka.AMPMS[12<=b&&24>b?1:0]},s_cEd=function(a,b,c,d,e,f){var g=b.length;switch(b.charAt(0)){case "G":return c=0<d.getFullYear()?1:0,4<=g?a.ka.d8c[c]:a.ka.Hec[c];case "y":return c=d.getFullYear(),0>c&&(c=-c),2==g&&(c%=100),s_vC(a,s_0g(c,g));case "Y":return c=d.getMonth(),e=d.getDate(),c=s_3Dd(d.getFullYear(),c,e,a.ka.Tcb,a.ka.Qfa),c=(new Date(c)).getFullYear(),0>c&&(c=-c),2==g&&(c%=100),s_vC(a,s_0g(c,g));
case "M":a:switch(c=d.getMonth(),g){case 5:g=a.ka.Xhd[c];break a;case 4:g=a.ka.Aeb[c];break a;case 3:g=a.ka.mDb[c];break a;default:g=s_vC(a,s_0g(c+1,g))}return g;case "k":return s_dEd(e),c=s_aEd(e)||24,s_vC(a,s_0g(c,g));case "S":return s_vC(a,(e.getMilliseconds()/1E3).toFixed(Math.min(3,g)).slice(2)+(3<g?s_0g(0,g-3):""));case "E":return c=d.getDay(),4<=g?a.ka.CDb[c]:a.ka.nDb[c];case "a":return s_eEd(a,e);case "b":return s_eEd(a,e);case "B":return s_eEd(a,e);case "h":return s_dEd(e),c=s_aEd(e)%12||
12,s_vC(a,s_0g(c,g));case "K":return s_dEd(e),c=s_aEd(e)%12,s_vC(a,s_0g(c,g));case "H":return s_dEd(e),c=s_aEd(e),s_vC(a,s_0g(c,g));case "c":a:switch(c=d.getDay(),g){case 5:g=a.ka.zUa[c];break a;case 4:g=a.ka.fkd[c];break a;case 3:g=a.ka.Ikc[c];break a;default:g=s_vC(a,s_0g(c,1))}return g;case "L":a:switch(c=d.getMonth(),g){case 5:g=a.ka.ekd[c];break a;case 4:g=a.ka.EHa[c];break a;case 3:g=a.ka.Hkc[c];break a;default:g=s_vC(a,s_0g(c+1,g))}return g;case "Q":return c=Math.floor(d.getMonth()/3),4>g?
a.ka.Dkc[c]:a.ka.zkc[c];case "d":return s_vC(a,s_0g(d.getDate(),g));case "m":return s_dEd(e),s_vC(a,s_0g(e.getMinutes?e.getMinutes():0,g));case "s":return s_dEd(e),s_vC(a,s_0g(e.getSeconds(),g));case "v":return(f||s_tC(c.getTimezoneOffset())).wa;case "V":return a=f||s_tC(c.getTimezoneOffset()),2>=g?a.wa:0<s_6Dd(a,c)?void 0!==a.ka.Q7c?a.ka.Q7c:a.ka.DST_GENERIC_LOCATION:void 0!==a.ka.Lkc?a.ka.Lkc:a.ka.STD_GENERIC_LOCATION;case "w":return c=e.getMonth(),d=e.getDate(),c=s_3Dd(e.getFullYear(),c,d,a.ka.Tcb,
a.ka.Qfa),s_vC(a,s_0g(Math.floor(Math.round((c-(new Date((new Date(c)).getFullYear(),0,1)).valueOf())/864E5)/7)+1,g));case "z":return a=f||s_tC(c.getTimezoneOffset()),4>g?a.Aa[0<s_6Dd(a,c)?2:0]:a.Aa[0<s_6Dd(a,c)?3:1];case "Z":return d=f||s_tC(c.getTimezoneOffset()),4>g?(g=-s_7Dd(d,c),a=[0>g?"-":"+"],g=Math.abs(g),a.push(s_0g(Math.floor(g/60)%100,2),s_0g(g%60,2)),g=a.join("")):g=s_vC(a,s_5Dd(s_7Dd(d,c))),g;default:return""}};

}catch(e){_DumpException(e)}
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var s_fEd={Ueb:"y",nmd:"y G",CUa:"MMM y",fna:"MMMM y",omd:"MM/y",kga:"MMM d",Mjc:"MMMM dd",Beb:"M/d",OCb:"MMMM d",Zua:"MMM d, y",j6:"EEE, MMM d",gmd:"EEE, MMM d, y",Cec:"d",Sff:"MMM d, h:mm a zzzz"},s_wC=s_fEd;s_wC=s_fEd;

}catch(e){_DumpException(e)}
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var s_iEd=new s_gx(0,0,1),s_jEd=new s_gx(9999,11,31);

}catch(e){_DumpException(e)}
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var s_kEd=function(a){this.ka=a.oa.clone();this.oa=Number(a.ka.Hf())};s_Se(s_kEd,s_1i);s_kEd.prototype.next=function(){if(Number(this.ka.Hf())>this.oa)return s_2i;var a=this.ka.clone();this.ka.add(new s_fx("d",1));return s_3i(a)};var s_lEd=function(){this.oa=s_iEd;this.ka=s_jEd};s_lEd.prototype.contains=function(a){return a.valueOf()>=this.oa.valueOf()&&a.valueOf()<=this.ka.valueOf()};s_lEd.prototype.iterator=function(){return new s_kEd(this)};
var s_mEd=function(a,b){this.ka=a;this.oa=b||s_5d()};
s_mEd.prototype.Ba=function(a,b,c,d){b?(d=s_4d(this.oa,"TD"),d.colSpan=c?1:2,s_xC(this,d,"\u00ab",this.ka+"-previousMonth"),a.appendChild(d),d=s_4d(this.oa,"TD"),d.colSpan=c?6:5,d.className=this.ka+"-monthyear",a.appendChild(d),d=s_4d(this.oa,"TD"),s_xC(this,d,"\u00bb",this.ka+"-nextMonth"),a.appendChild(d)):(c=s_4d(this.oa,"TD"),c.colSpan=5,s_xC(this,c,"\u00ab",this.ka+"-previousMonth"),s_xC(this,c,"",this.ka+"-month"),s_xC(this,c,"\u00bb",this.ka+"-nextMonth"),b=s_4d(this.oa,"TD"),b.colSpan=3,s_xC(this,
b,"\u00ab",this.ka+"-previousYear"),s_xC(this,b,"",this.ka+"-year"),s_xC(this,b,"\u00bb",this.ka+"-nextYear"),d.indexOf("y")<d.indexOf("m")?(a.appendChild(b),a.appendChild(c)):(a.appendChild(c),a.appendChild(b)))};
s_mEd.prototype.wa=function(a,b){var c=s_4d(this.oa,"TD");c.colSpan=b?2:3;c.className=this.ka+"-today-cont";s_xC(this,c,"Today",this.ka+"-today-btn");a.appendChild(c);c=s_4d(this.oa,"TD");c.colSpan=b?4:3;a.appendChild(c);c=s_4d(this.oa,"TD");c.colSpan=2;c.className=this.ka+"-none-cont";s_xC(this,c,"None",this.ka+"-none-btn");a.appendChild(c)};var s_xC=function(a,b,c,d){var e=[a.ka+"-btn"];d&&e.push(d);d=s_4d(a.oa,"BUTTON");d.className=e.join(" ");d.appendChild(s_roa(a.oa,c));b.appendChild(d)};
var s_yC=function(a,b,c,d){s_2s.call(this,c);this.Ba=b||s_ex;this.he=this.Ba.Ikc;this.vk=new s_uC("d",this.Ba);new s_uC("dd",this.Ba);this.rr=new s_uC("w",this.Ba);this.wo=new s_uC("d MMM",this.Ba);this.Lc=new s_uC(s_wC.Ueb||"y",this.Ba);this.Nl=new s_uC(s_wC.fna||"MMMM y",this.Ba);this.Ee=d||new s_mEd(this.Jo(),this.ka);this.wa=new s_gx(a);this.wa.Lxa=this.Ba.Tcb;this.wa.v7=this.Ba.Qfa;this.oa=this.wa.clone();this.oa.setDate(1);this.Pb="      ".split(" ");this.Pb[this.Ba.tlc[0]]=this.Jo()+"-wkend-start";
this.Pb[this.Ba.tlc[1]]=this.Jo()+"-wkend-end";this.Sa={};this.Oa=[];this.Tc=0};s_Se(s_yC,s_2s);s_=s_yC.prototype;s_.Yub=!0;s_.Ecc=new s_lEd;s_.jvb=!0;s_.kvb=!0;s_.dIa=!0;s_.ivb=!0;s_.A9b=!1;s_.Thb=null;s_.Aib=null;s_.zib=null;s_.yib=null;s_.fsd=s_nkc.Tb();s_.Jo=function(){return"goog-date-picker"};var s_oEd=function(a){a.A9b=!0;s_nEd(a);s_zC(a)},s_qEd=function(a){a.jvb=!1;s_nEd(a);s_pEd(a);s_zC(a)},s_rEd=function(a){s_E(a.Lb,a.ivb);s_E(a.Db,a.dIa);s_E(a.Fh,a.ivb||a.dIa)};s_=s_yC.prototype;
s_.w3b=function(){this.oa.add(new s_fx("m",-1));s_zC(this);s_sEd(this)};s_.HBa=function(){this.oa.add(new s_fx("m",1));s_zC(this);s_sEd(this)};s_.zFe=function(){this.oa.add(new s_fx("y",-1));s_zC(this);s_sEd(this)};s_.ane=function(){this.oa.add(new s_fx("y",1));s_zC(this);s_sEd(this)};s_.dWc=function(){this.setDate(new s_gx)};s_.U6b=function(){this.dIa&&this.setDate(null)};s_.getDate=function(){return this.wa&&this.wa.clone()};s_.setDate=function(a){s_tEd(this,a,!0)};
var s_tEd=function(a,b,c){var d=b==a.wa||b&&a.wa&&b.getFullYear()==a.wa.getFullYear()&&b.getMonth()==a.wa.getMonth(),e=b==a.wa||d&&b.getDate()==a.wa.getDate();a.wa=b&&new s_gx(b);b&&(a.oa.set(a.wa),a.oa.setFullYear(a.wa.getFullYear()),a.oa.setDate(1));s_zC(a);c&&a.dispatchEvent(new s_uEd("select",a,a.wa));e||a.dispatchEvent(new s_uEd("change",a,a.wa));d||s_sEd(a)},s_nEd=function(a){if(a.Aib){for(var b=a.Aib;b.firstChild;)b.removeChild(b.firstChild);a.Ee.Ba(b,a.A9b,a.jvb,a.Ba.rua[0].toLowerCase());
if(a.A9b){s_AC(a,b,a.Jo()+"-previousMonth",a.w3b);var c=s_C(a.Jo()+"-previousMonth",b);c&&(s_Fr(c,"hidden",!0),c.tabIndex=-1);s_AC(a,b,a.Jo()+"-nextMonth",a.HBa);if(c=s_C(a.Jo()+"-nextMonth",b))s_Fr(c,"hidden",!0),c.tabIndex=-1;a.zib=s_C(a.Jo()+"-monthyear",b)}else s_AC(a,b,a.Jo()+"-previousMonth",a.w3b),s_AC(a,b,a.Jo()+"-nextMonth",a.HBa),s_AC(a,b,a.Jo()+"-month",a.ASe),s_AC(a,b,a.Jo()+"-previousYear",a.zFe),s_AC(a,b,a.Jo()+"-nextYear",a.ane),s_AC(a,b,a.Jo()+"-year",a.zTe),a.Ma=s_C(a.Jo()+"-month",
b),c=s_5d(),b=s_C(a.Jo()+"-year",b||c.ka),a.Hb=b}},s_AC=function(a,b,c,d){b=s_C(c,b);s_4s(a).listen(b,"click",function(e){e.preventDefault();d.call(this,e)})},s_pEd=function(a){if(a.yib){var b=a.yib;s_nh(b);a.Ee.wa(b,a.jvb);s_AC(a,b,a.Jo()+"-today-btn",a.dWc);s_AC(a,b,a.Jo()+"-none-btn",a.U6b);a.Lb=s_C(a.Jo()+"-today-btn",b);a.Db=s_C(a.Jo()+"-none-btn",b);s_rEd(a)}};s_=s_yC.prototype;
s_.oA=function(a){s_yC.Wc.oA.call(this,a);s_qj(a,this.Jo());var b=this.ka.Bh("TABLE",{role:"presentation"}),c=this.ka.Bh("THEAD"),d=this.ka.Bh("TBODY",{role:"grid"}),e=this.ka.Bh("TFOOT");d.tabIndex=0;this.ah=d;this.Fh=e;var f=this.ka.Bh("TR",{role:"row"});f.className=this.Jo()+"-head";this.Aib=f;s_nEd(this);c.appendChild(f);this.Da=[];for(var g=0;7>g;g++){f=s_4d(this.ka,"TR");this.Da[g]=[];for(var k=0;8>k;k++){var h=s_4d(this.ka,0==k||0==g?"th":"td");0!=k&&0!=g||k==g?0!==g&&0!==k&&(s_Dr(h,"gridcell"),
h.setAttribute("tabindex","-1")):(h.className=0==k?this.Jo()+"-week":this.Jo()+"-wday",s_Dr(h,0==k?"rowheader":"columnheader"));f.appendChild(h);this.Da[g][k]=h}d.appendChild(f)}f=s_4d(this.ka,"TR");f.className=this.Jo()+"-foot";this.yib=f;s_pEd(this);e.appendChild(f);b.cellSpacing="0";b.cellPadding="0";b.appendChild(c);b.appendChild(d);b.appendChild(e);a.appendChild(b);s_vEd(this);s_zC(this);a.tabIndex=0};s_.Bw=function(){s_yC.Wc.Bw.call(this);this.oA(this.Ca())};
s_.Am=function(){s_yC.Wc.Am.call(this);var a=s_4s(this);a.listen(this.ah,"click",this.q0d);a.listen(s_wEd(this,this.Ca()),"key",this.s0d)};s_.Jw=function(){s_yC.Wc.Jw.call(this);this.Ra();for(var a in this.Sa)this.Sa[a].dispose();this.Sa={}};s_.create=s_yC.prototype.Ej;s_.kc=function(){s_yC.Wc.kc.call(this);this.Db=this.Lb=this.Hb=this.zib=this.Ma=this.yib=this.Aib=this.Fh=this.ah=this.Da=null};
s_.q0d=function(a){if("TD"==a.target.tagName){var b,c=-2,d=-2;for(b=a.target;b;b=b.previousSibling,c++);for(b=a.target.parentNode;b;b=b.previousSibling,d++);a=this.Oa[d][c];this.Ecc.contains(a)&&this.setDate(a.clone())}};
s_.s0d=function(a){switch(a.keyCode){case 33:a.preventDefault();var b=-1;break;case 34:a.preventDefault();b=1;break;case 37:a.preventDefault();var c=-1;break;case 39:a.preventDefault();c=1;break;case 38:a.preventDefault();c=-7;break;case 40:a.preventDefault();c=7;break;case 36:a.preventDefault();this.dWc();break;case 46:a.preventDefault();this.U6b();break;case 13:case 32:a.preventDefault(),s_tEd(this,this.wa,!0);default:return}this.wa?(a=this.wa.clone(),a.add(new s_fx(0,b,c))):(a=this.oa.clone(),
a.setDate(1));this.Ecc.contains(a)&&(s_tEd(this,a,!1),this.Ht.focus())};s_.ASe=function(a){a.stopPropagation();a=[];for(var b=0;12>b;b++)a.push(this.Ba.EHa[b]);s_xEd(this,this.Ma,a,this.V2d,this.Ba.EHa[this.oa.getMonth()])};s_.zTe=function(a){a.stopPropagation();a=[];for(var b=this.oa.getFullYear(),c=this.oa.clone(),d=-5;5>=d;d++)c.setFullYear(b+d),a.push(this.Lc.format(c));s_xEd(this,this.Hb,a,this.W7d,this.Lc.format(this.oa))};
s_.V2d=function(a){a=Number(a.getAttribute("itemIndex"));this.oa.setMonth(a);s_zC(this);this.Ma.focus&&this.Ma.focus()};s_.W7d=function(a){3==a.firstChild.nodeType&&(a=Number(a.getAttribute("itemIndex")),this.oa.setFullYear(this.oa.getFullYear()+a-5),s_zC(this));this.Hb.focus()};
var s_xEd=function(a,b,c,d,e){a.Ra();var f=s_4d(a.ka,"DIV");f.className=a.Jo()+"-menu";a.kb=null;for(var g=s_4d(a.ka,"UL"),k=0;k<c.length;k++){var h=a.ka.Bh("LI",null,c[k]);h.setAttribute("itemIndex",k);c[k]==e&&(a.kb=h);g.appendChild(h)}f.appendChild(g);f.style.left=b.offsetLeft+b.parentNode.offsetLeft+"px";f.style.top=b.offsetTop+"px";f.style.width=b.clientWidth+"px";a.Ma.parentNode.appendChild(f);a.Ga=f;a.kb||(a.kb=g.firstChild);a.kb.className=a.Jo()+"-menu-selected";a.Zc=d;b=s_4s(a);b.listen(a.Ga,
"click",a.Ef);b.listen(s_wEd(a,a.Ga),"key",a.Lg);b.listen(a.ka.Ze(),"click",a.Ra);f.tabIndex=0;f.focus()};s_yC.prototype.Ef=function(a){a.stopPropagation();this.Ra();this.Zc&&this.Zc(a.target)};
s_yC.prototype.Lg=function(a){a.stopPropagation();var b=this.kb;switch(a.keyCode){case 35:a.preventDefault();var c=b.parentNode.lastChild;break;case 36:a.preventDefault();c=b.parentNode.firstChild;break;case 38:a.preventDefault();c=b.previousSibling;break;case 40:a.preventDefault();c=b.nextSibling;break;case 13:case 9:case 0:a.preventDefault(),this.Ra(),this.Zc(b)}c&&c!=b&&(b.className="",c.className=this.Jo()+"-menu-selected",this.kb=c)};
s_yC.prototype.Ra=function(){if(this.Ga){var a=s_4s(this);a.unlisten(this.Ga,"click",this.Ef);a.unlisten(s_wEd(this,this.Ga),"key",this.Lg);a.unlisten(this.ka.Ze(),"click",this.Ra);s_rh(this.Ga);delete this.Ga}};
var s_zC=function(a){if(a.Ca()){var b=a.oa.clone();b.setDate(1);a.zib&&s_yh(a.zib,a.Nl.format(b));a.Ma&&s_yh(a.Ma,a.Ba.EHa[b.getMonth()]);a.Hb&&s_yh(a.Hb,a.Lc.format(b));var c=b.ica();s_2Dd(b);b.add(new s_fx("m",-1));b.setDate(s_2Dd(b)-(c-1));c=new s_fx("d",1);a.Oa=[];for(var d=0;6>d;d++){a.Oa[d]=[];for(var e=0;7>e;e++){a.Oa[d][e]=b.clone();var f=b.getFullYear();b.add(c);0==b.getMonth()&&1==b.getDate()&&f++;b.setFullYear(f)}}s_yEd(a)}},s_yEd=function(a){if(a.Ca()){var b=a.oa.getMonth(),c=new s_gx,
d=c.getFullYear(),e=c.getMonth();c=c.getDate();for(var f=6,g=0;6>g;g++){a.jvb?(s_yh(a.Da[g+1][0],a.rr.format(a.Oa[g][0])),s_oj(a.Da[g+1][0],a.Jo()+"-week")):(s_yh(a.Da[g+1][0],""),s_oj(a.Da[g+1][0],""));for(var k=0;7>k;k++){var h=a.Oa[g][k],l=a.Da[g+1][k+1];l.id||(l.id=s_okc(a.fsd));s_Dr(l,"gridcell");s_Ir(l,a.wo.format(h));var m=[a.Jo()+"-date"];a.Ecc.contains(h)||m.push(a.Jo()+"-unavailable-date");h.getMonth()!=b&&m.push(a.Jo()+"-other-month");var n=(k+a.oa.v7+7)%7;a.Pb[n]&&m.push(a.Pb[n]);h.getDate()==
c&&h.getMonth()==e&&h.getFullYear()==d&&m.push(a.Jo()+"-today");a.wa&&h.getDate()==a.wa.getDate()&&h.getMonth()==a.wa.getMonth()&&h.getFullYear()==a.wa.getFullYear()&&(m.push(a.Jo()+"-selected"),a.Ht=l);a.Thb&&(n=a.Thb(h))&&m.push(n);h=a.vk.format(h);s_yh(l,h);s_oj(l,m.join(" "))}4<=g&&(k=a.Da[g+1][0].parentElement||a.Da[g+1][0].parentNode,l=a.Oa[g][0].getMonth()==b,s_E(k,l||a.Yub),l||(f=Math.min(f,g)))}b=(a.Yub?6:f)+(a.kvb?1:0);a.Tc!=b&&(a.Tc<b&&a.dispatchEvent("gridSizeIncrease"),a.Tc=b)}},s_sEd=
function(a){var b=new s_uEd("changeActiveMonth",a,a.oa.clone());a.dispatchEvent(b)},s_vEd=function(a){if(a.Ca()){if(a.kvb)for(var b=0;7>b;b++)s_yh(a.Da[0][b+1],a.he[((b+a.oa.v7+7)%7+1)%7]);s_E(a.Da[0][0].parentElement||a.Da[0][0].parentNode,a.kvb)}},s_wEd=function(a,b){var c=s_Fa(b);c in a.Sa||(a.Sa[c]=new s_ow(b));return a.Sa[c]},s_uEd=function(a,b,c){s_sg.call(this,a,b);this.date=c};s_Se(s_uEd,s_sg);

}catch(e){_DumpException(e)}
try{
var s_Y6l=function(a){return a.replace(/_/g,"_1").replace(/,/g,"_2").replace(/:/g,"_3")};

}catch(e){_DumpException(e)}
try{
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var s_bcm=function(a){this.ka=[];this.oa=s_ex;if("number"==typeof a){11<a&&(a=10);if(4>a)var b=this.oa.rua[a];else 8>a?b=this.oa.fva[a-4]:(b=this.oa.Bec[a-8],b=b.replace("{1}",this.oa.rua[a-8]),b=b.replace("{0}",this.oa.fva[a-8]));s_acm(this,b)}else s_acm(this,a)},s_acm=function(a,b){for(var c=!1,d="",e=0;e<b.length;e++){var f=b.charAt(e);if(" "==f)for(0<d.length&&(a.ka.push({text:d,count:0,jva:!1,numeric:!1}),d=""),a.ka.push({text:" ",count:0,jva:!1,numeric:!1});e<b.length-1&&" "==b.charAt(e+1);)e++;
else if(c)"'"==f?e+1<b.length&&"'"==b.charAt(e+1)?(d+="'",e++):c=!1:d+=f;else if(0<="GyMdkHmsSEDabBhKzZvQL".indexOf(f)){0<d.length&&(a.ka.push({text:d,count:0,jva:!1,numeric:!1}),d="");for(var g=b.charAt(e),k=e+1;k<b.length&&b.charAt(k)==g;)k++;g=k-e;0>=g?k=!1:(k="MydhHmsSDkK".indexOf(f),k=0<k||0==k&&3>g);a.ka.push({text:f,count:g,jva:!1,numeric:k});e+=g-1}else"'"==f?e+1<b.length&&"'"==b.charAt(e+1)?(d+="'",e++):c=!0:d+=f}0<d.length&&a.ka.push({text:d,count:0,jva:!1,numeric:!1});b=!1;for(c=0;c<a.ka.length;c++)a.ka[c].numeric?
!b&&c+1<a.ka.length&&a.ka[c+1].numeric&&(b=!0,a.ka[c].jva=!0):b=!1};
s_bcm.prototype.parse=function(a,b,c){var d=!1,e=!1;c&&(d=c.Eyf||!1,e=c.validate||!1);if(d)for(c=0;c<this.ka.length;c++){var f=this.ka[c];if(0<f.count&&(0>"abBhHkKm".indexOf(f.text.charAt(0))||2<f.count||f.jva))throw Error("Ik`"+f.text.charAt(0));}f=new s_ccm;c=[0];f.La=null;for(var g=0;g<this.ka.length&&!(d&&c[0]>=a.length);g++){if(0==this.ka[g].count){a:{var k=a;var h=this.ka[g],l=d;if(" "==h.text.charAt(0)){if(h=c[0],s_dcm(k,c),c[0]>h){k=!0;break a}}else{if(k.indexOf(h.text,c[0])==c[0]){c[0]+=
h.text.length;k=!0;break a}if(l&&0==h.text.indexOf(k.substring(c[0]))){c[0]+=k.length-c[0];k=!0;break a}}k=!1}if(k)continue;return 0}if(this.ka[g].jva){a:{h=a;l=g;var m=c[0],n=0;for(k=l;k<this.ka.length;k++){var p=this.ka[k],q=p.count;if(0===q)break;if(k==l&&(q-=n,n++,0==q)){k=0;break a}var r=k>l&&p.numeric,t=c[0];if(!s_ecm(this,h,c,p,q,f,!1)||r&&c[0]-t<q)k=l-1,c[0]=m}k-=l}if(0>=k)return 0;g+=k-1}else if(!s_ecm(this,a,c,this.ka[g],0,f,d))return 0}a:{a=e;if(null==b)throw Error("Jk");void 0!=f.era&&
void 0!=f.year&&0==f.era&&0<f.year&&(f.year=-(f.year-1));void 0!=f.year&&b.setFullYear(f.year);d=b.getDate();b.setDate(1);void 0!=f.month&&b.setMonth(f.month);void 0!=f.day?b.setDate(f.day):(e=s_oQc(b.getFullYear(),b.getMonth()),b.setDate(d>e?e:d));"function"===typeof b.setHours&&(void 0==f.hours&&(f.hours=b.getHours()),12>f.hours&&(void 0!=f.Ga&&0<f.Ga?f.hours+=12:void 0!==f.Aa&&("isPm noon afternoon1 afternoon2 evening1 evening2".split(" ").includes(f.Aa)||["night1","night2"].includes(f.Aa)&&6<=
f.hours)&&(f.hours+=12)),b.setHours(f.hours));"function"===typeof b.setMinutes&&void 0!=f.minutes&&b.setMinutes(f.minutes);"function"===typeof b.setSeconds&&void 0!=f.ka&&b.setSeconds(f.ka);"function"===typeof b.setMilliseconds&&void 0!=f.oa&&b.setMilliseconds(f.oa);if(a&&(f.year&&f.year!=b.getFullYear()||f.month&&f.month!=b.getMonth()||f.day&&f.day!=b.getDate()||f.hours&&24<=f.hours||f.minutes&&60<=f.minutes||f.ka&&60<=f.ka||f.oa&&1E3<=f.oa))b=!1;else{void 0!=f.Ba&&(a=b.getTimezoneOffset(),b.setTime(b.getTime()+
6E4*(f.Ba-a)));f.Da&&(a=new Date,a.setFullYear(a.getFullYear()-80),b.getTime()<a.getTime()&&b.setFullYear(a.getFullYear()+100));if(void 0!=f.wa)if(void 0==f.day)f=(7+f.wa-b.getDay())%7,3<f&&(f-=7),a=b.getMonth(),b.setDate(b.getDate()+f),b.getMonth()!=a&&b.setDate(b.getDate()+(0<f?-7:7));else if(f.wa!=b.getDay()){b=!1;break a}b=!0}}return b?c[0]:0};
var s_ecm=function(a,b,c,d,e,f,g){s_dcm(b,c);if(d.numeric&&0<e&&c[0]+e>b.length)return!1;switch(d.text.charAt(0)){case "G":return s_fcm(b,c,[a.oa.Hec],function(k){return f.era=k}),!0;case "M":case "L":return s_gcm(a,b,c,e,d,f);case "E":return s_fcm(b,c,[a.oa.CDb,a.oa.nDb],function(k){return f.wa=k});case "B":case "b":return a=[[].concat(a.oa.AMPMS)],b=s_fcm(b,c,a,function(k){return f.La=k},g),f.Aa=null,g?b:!0;case "a":return b=s_fcm(b,c,[a.oa.AMPMS],function(k){return f.Ga=k},g),g?b:!0;case "y":return s_hcm(a,
b,c,d,e,f);case "Q":return s_fcm(b,c,[a.oa.zkc,a.oa.Dkc],function(k){f.month=3*k;f.day=1});case "d":return s_icm(a,b,c,d,e,function(k){f.day=k}),!0;case "S":return s_jcm(a,b,c,e,f);case "h":case "K":case "H":case "k":return b=s_icm(a,b,c,d,e,function(k){f.hours="h"===d.text.charAt(0)&&12===k?0:k},g),g?b:!0;case "m":return b=s_icm(a,b,c,d,e,function(k){f.minutes=k},g),g?b:!0;case "s":return s_icm(a,b,c,d,e,function(k){f.ka=k}),!0;case "z":case "Z":case "v":return s_kcm(a,b,c,f);default:return!1}},
s_hcm=function(a,b,c,d,e,f){var g=c[0];e=s_lcm(a,b,c,e);null===e&&(e=s_lcm(a,b,c,0,!0));if(null===e)return!1;0<=e&&2==c[0]-g&&2==d.count?(a=e,b=(new Date).getFullYear()-80,c=b%100,f.Da=a==c,a+=100*Math.floor(b/100)+(a<c?100:0),f.year=a):f.year=e;return!0},s_gcm=function(a,b,c,d,e,f){return e.numeric&&s_icm(a,b,c,e,d,function(g){f.month=g-1})?!0:s_fcm(b,c,[a.oa.Aeb,a.oa.EHa,a.oa.mDb,a.oa.Hkc],function(g){f.month=g})},s_jcm=function(a,b,c,d,e){var f=c[0];a=s_lcm(a,b,c,d);if(null===a)return!1;c=c[0]-
f;e.oa=3>c?a*Math.pow(10,3-c):Math.round(a/Math.pow(10,c-3));return!0},s_kcm=function(a,b,c,d){b.indexOf("GMT",c[0])==c[0]&&(c[0]+=3);if(c[0]>=b.length)return d.Ba=0,!0;var e=c[0],f=s_lcm(a,b,c,0,!0);if(null===f)return!1;if(c[0]<b.length&&":"==b.charAt(c[0])){var g=60*f;c[0]++;f=s_lcm(a,b,c,0);if(null===f)return!1;g+=f}else g=f,g=24>g&&3>=c[0]-e?60*g:g%100+g/100*60;d.Ba=-g;return!0},s_icm=function(a,b,c,d,e,f,g){g=g||!1;var k=c[0];a=s_lcm(a,b,c,e);if(null===a)return!1;if(g&&c[0]-k<d.count){if(c[0]<
b.length)return!1;a*=Math.pow(10,d.count-(c[0]-k))}f(a);return!0},s_fcm=function(a,b,c,d,e){e=e||!1;for(var f,g=0;g<c.length;g++){f=b;for(var k=c[g],h=e,l=0,m=null,n=a.substring(f[0]).toLowerCase(),p=0;p<k.length;p++){var q=k[p].toLowerCase();if(h&&0==q.indexOf(n)){l=n.length;m=p;break}k[p].length>l&&0==n.indexOf(q)&&(l=k[p].length,m=p)}null!==m&&(f[0]+=l);f=m;if(null!==f)return d(f),!0}return!1},s_dcm=function(a,b){(a=a.substring(b[0]).match(/^\s+/))&&(b[0]+=a[0].length)},s_lcm=function(a,b,c,d,
e){b=0<d?b.substring(0,c[0]+d):b;e=e||!1;if(a.oa.FDb){d=[];for(var f=c[0];f<b.length;f++){var g=b.charCodeAt(f)-a.oa.FDb;d.push(0<=g&&9>=g?String.fromCharCode(g+48):b.charAt(f))}b=d.join("")}else b=b.substring(c[0]);a=b.match(new RegExp("^"+(e?"[+-]?":"")+"\\d+"));if(!a)return null;c[0]+=a[0].length;return parseInt(a[0],10)},s_ccm=function(){};s_ccm.prototype.Da=!1;

}catch(e){_DumpException(e)}
try{
s_a("VD4Qme");

var s_mcm=function(){var a={};a=(a.OouJcb="cd_min",a.rzG2be="cd_max",a);var b=s_Tb("HjtPBb");if(b)for(var c in a){var d=s_Tb(c);b.value=b.value.replace(new RegExp("("+a[c]+":)([^,]*)"),"$1"+s_Y6l(d.value).replace(/^\s+|\s+$/g,""))}},s_ocm=function(a){var b=s_ncm();a.Thb=b},s_pcm=s_kQc.rua[3],s_$P=function(a){s_m.call(this,a.Ka);this.oa=this.link=this.container=this.ka=null;this.Aa=!0;this.Ba=this.getData("m").Mb()};s_q(s_$P,s_m);s_$P.Ea=s_m.Ea;s_$P.prototype.NLd=function(){return this.ka};
s_$P.prototype.XId=function(){return this.oa};s_$P.prototype.Cb=function(){this.p8();s_zg(window,"resize",this.wa)};var s_qcm=function(a,b){var c=new Date,d=new s_bcm(s_pcm);b=b.value.trim();if(0===b.length||d.parse(b,c,{validate:!0})!==b.length)a.oa.U6b();else{a.Aa=!1;try{a.oa.setDate(c)}finally{a.Aa=!0}}},s_rcm=function(a){var b=a.oa.getDate();if(a.Aa&&b){var c=new s_uC(s_pcm.replace(/yy/,"y"));a.ka.value=c.format(b);"OouJcb"===a.ka.id?s_5g("rzG2be").focus():a.ka.focus()}};s_$P.prototype.eQe=function(){s_rcm(this)};
var s_scm=function(a,b){var c=s_C("qomYCd",a.container);s_uj(c,"KbfSHd","OouJcb"!==b.id);s_Wi(function(){s_qj(c,"lRiKjb");s_jc(function(){s_sj(c,"lRiKjb")})},150)},s_tcm=function(){var a=s_C("goog-date-picker-head");return a&&(a=s_8g("goog-date-picker-btn",a))&&1<a.length?a[1]:null};s_$P.prototype.VLd=function(){return s_tcm()};
var s_ncm=function(){var a=new Date(Date.now());a.setDate(28);var b,c=new Date(Date.now());return function(d){b||(b=s_tcm());b&&s_uj(b,"suap3e",Number(a)<=Number(d));return Number(d)<=Number(c)?null:"suap3e"}};s_$P.prototype.xje=function(){return s_ncm()};
var s_vcm=function(a){var b=s_hh("DIV","UfY8P");s_lh(s_C("NwEGxd",a.container),b);var c=new s_yC;s_qEd(c);c.ivb=!1;c.Lb&&s_rEd(c);c.Yub=!0;s_zC(c);c.dIa=!0;c.Db&&s_rEd(c);c.he=c.Ba.zUa;s_vEd(c);s_oEd(c);s_ocm(c);c.Ej(b);a.oa=c;var d=s_C("Gwgzqd",a.container),e=s_C("Ru1Ao",a.container);b=s_Tb("OouJcb");var f=s_Tb("rzG2be");s_l(c,"select",function(){return s_rcm(a)});s_l(a.container,"keyup",function(g){27===g.keyCode&&a.p8()});s_l(d,"keydown",function(g){9===g.keyCode&&g.shiftKey&&(g.preventDefault(),
e.focus())});s_l(e,"keydown",function(g){9!==g.keyCode||g.shiftKey||(g.preventDefault(),d.focus())});s_l(e,"click",function(){for(var g=[s_Tb("OouJcb"),s_Tb("rzG2be")],k=new Date,h=new s_bcm(s_pcm),l=new s_uC(s_pcm.replace(/yy/,"y")),m=0;m<g.length;m++){var n=g[m],p=n.value.trim();0!==p.length&&h.parse(p,k,{validate:!0})===p.length&&(n.value=l.format(k))}});s_ucm(a,b);s_ucm(a,f);s_l(window,"resize",function(){return a.wa()})};
s_$P.prototype.wa=function(){if(this.container){var a=this.container,b=Math.max(s_C("tmDYm",a).clientWidth,s_C("iWBKNe",a).clientWidth),c=s_Vu()?"right":"left",d=s_C("J6UZg",a),e=s_ii(document.body||document.documentElement),f=s_ii(d),g=f.width+b;g<e.width?(d.style.width=g+"px",s_C("NwEGxd",a).style[c]=b+"px",s_sj(d,"QIQ7Cc")):(d.style.width=e.width+"px",s_C("NwEGxd",a).style[c]="0",s_qj(d,"QIQ7Cc"));this.Ba?(a=s_lw(0,!0),s_Ub(d)+f.height<=a?d.style.top="":d.style.top=Math.max(0,a-f.height)+"px"):
d.style.top="0"}};s_$P.prototype.Qnd=function(){this.wa()};var s_ucm=function(a,b){s_l(b,"keyup",function(c){s_qcm(a,b);27===c.keyCode&&a.p8()})};s_$P.prototype.tca=function(a){this.ka=a=a.actionElement.el();s_scm(this,a);s_qcm(this,a)};s_$P.prototype.p8=function(){if(this.link){var a=s_Tb("top_nav");a:{for(var b=this.link.parentElement;b&&b!==a;b=b.parentElement)if(b.hasAttribute("role")){a=b;break a}a=null}a.focus();this.link=null}this.container&&(this.container.style.display="none",this.ka=null)};
s_$P.prototype.BRe=function(a){(a=a.actionElement.el())&&s_wcm(this,a)};var s_wcm=function(a,b){a.link=b;a.container||(b=s_C("n5Ug4b",b.parentElement),s_lh(s_Tb("top_nav"),b),b.style.display="block",a.container=b,s_cd(a.container,a.getRoot().el()),s_vcm(a));a.container.style.display="block";a.wa();var c=s_Tb("OouJcb");s_qcm(a,c);s_jc(function(){c.focus()})};s_$P.prototype.Ura=function(){s_mcm()};s_$P.prototype.zEa=function(){s_mcm();s_Tb("T3kYXe").submit()};s_I(s_$P.prototype,"hNEEAb",function(){return this.zEa});
s_I(s_$P.prototype,"zbvklb",function(){return this.Ura});s_I(s_$P.prototype,"EEGHee",function(){return this.BRe});s_I(s_$P.prototype,"xp3IKd",function(){return this.p8});s_I(s_$P.prototype,"daRB0b",function(){return this.tca});s_I(s_$P.prototype,"Rb1Mac",function(){return this.Qnd});s_I(s_$P.prototype,"Kpa0wd",function(){return this.xje});s_I(s_$P.prototype,"jFBxGd",function(){return this.VLd});s_I(s_$P.prototype,"VUQXyf",function(){return this.eQe});s_I(s_$P.prototype,"k4Iseb",function(){return this.Cb});
s_I(s_$P.prototype,"wUeKKe",function(){return this.XId});s_I(s_$P.prototype,"wKX3te",function(){return this.NLd});s_T(s_ePa,s_$P);

s_b();

}catch(e){_DumpException(e)}
try{
var s_2zd=function(a,b,c){c=void 0===c?"m":c;var d=void 0===d?!0:d;var e=void 0===e?a:e;if(s_fc("l")){var f=window.localStorage;e=new s_tfa("l",e);b=s_e(b);for(var g=b.next();!g.done;g=b.next()){g=g.value;var k=a+"::"+g,h=f.getItem(k);d&&f.removeItem(k);null===e.get(g)&&null!==h&&(k=JSON.parse(h),null!==k&&e.set(g,k,c))}}};

}catch(e){_DumpException(e)}
try{
s_a("Exk9Ld");

var s_Uwm={name:"abar"},s_Vwm=function(a){s_m.call(this,a.Ka);s_2zd(s_Uwm.name,["bbh"],"h");a=s_Tc("l",s_Uwm);var b=1===a.get("bbh");this.getData("showSafesearchGlobalNotice").Mb(!1)?a.set("bbh",1,"h"):b||(this.getRoot().show(),a.set("bbh",1,"h"))};s_q(s_Vwm,s_m);s_Vwm.Ea=s_m.Ea;s_Vwm.prototype.M$d=function(){this.getRoot().hide()};s_I(s_Vwm.prototype,"R194mf",function(){return this.M$d});s_T(s_0Xa,s_Vwm);

s_b();

}catch(e){_DumpException(e)}
try{
s_a("GGTOgd");

var s_Wwm=function(a){s_m.call(this,a.Ka);this.kd=a.service.navigation};s_q(s_Wwm,s_m);s_Wwm.Ea=function(){return{service:{navigation:s_kv}}};s_Wwm.prototype.y9b=function(a){var b=s_H(this,"BFbLfd").el();b&&s_U(b);a=null==a.targetElement.Ic("checked");b=s_Bi(this.getRoot().getData(a?"setprefsOnUrl":"setprefsOffUrl"),"");s_mv(this.kd,s_Nb(b));this.getRoot().setData("safeSearchEnabled",a?"1":"0");a&&this.evc();return!0};s_Wwm.prototype.evc=function(){s_Tc("l",s_Uwm).remove("bbh")};
s_I(s_Wwm.prototype,"CojpKc",function(){return this.evc});s_I(s_Wwm.prototype,"hqPouf",function(){return this.y9b});s_T(s_aYa,s_Wwm);

s_b();

}catch(e){_DumpException(e)}
// Google Inc.
